# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180123_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='gauge',
            name='unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
